[build]
  command = "npm run build"
  publish = "out"

# Headers to ensure proper content types and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "*.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.svg"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_USE_NETLIFY_EDGE = "true"
  # Remove any API keys or sensitive information
  # Add environment variables through the Netlify dashboard instead