[build]
  command = "npm run build"
  publish = "out"

# Headers to ensure proper content types and caching
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' https://*.elfsight.com https://static.elfsight.com https://*.googleusercontent.com https://*.instagram.com https://*.cdninstagram.com https://*.gstatic.com https://*.firebase.googleapis.com https://maps.googleapis.com https://www.google.com https://widgets.sociablekit.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.elfsight.com https://static.elfsight.com https://*.elfsightcdn.com https://universe-static.elfsightcdn.com https://core.service.elfsight.com https://*.gstatic.com https://*.googleapis.com https://*.firebase.googleapis.com https://*.google.com https://g.doubleclick.net https://maps.googleapis.com https://widgets.sociablekit.com; style-src 'self' 'unsafe-inline' https://*.elfsight.com https://fonts.googleapis.com https://*.gstatic.com https://*.google.com; img-src 'self' data: https://*.googleusercontent.com https://*.instagram.com https://*.cdninstagram.com https://*.elfsight.com https://*.elfsightcdn.com https://lh3.googleusercontent.com https://phosphor.utils.elfsightcdn.com https://*.service.elfsight.com https://*.googleapis.com https://*.ggpht.com https://*.google.com https://maps.gstatic.com blob:; font-src 'self' data: https://fonts.gstatic.com https://*.elfsight.com https://*.elfsightcdn.com; media-src 'self' https://video.wixstatic.com https://*.elfsight.com https://*.elfsightcdn.com blob:; connect-src 'self' https://*.elfsight.com https://widget-data.service.elfsight.com https://*.service.elfsight.com https://*.googleapis.com https://*.instagram.com https://*.gstatic.com https://*.firebase.googleapis.com https://lh3.googleusercontent.com https://scontent.cdninstagram.com https://core.service.elfsight.com https://maps.googleapis.com https://www.google.com https://g.doubleclick.net https://accounts.google.com https://widgets.sociablekit.com; frame-src 'self' https://*.elfsight.com https://core.service.elfsight.com https://*.google.com https://g.doubleclick.net https://accounts.google.com https://www.gstatic.com https://maps.googleapis.com https://www.google.com/maps/ https://www.google.com/maps/embed; child-src 'self' blob: https://*.google.com https://maps.googleapis.com https://www.google.com/maps/; worker-src 'self' blob:; object-src 'none'; base-uri 'self';"
    Permissions-Policy = "accelerometer=*, autoplay=*, bluetooth=*, camera=*, clipboard-read=*, clipboard-write=*, cross-origin-isolated=*, display-capture=*, encrypted-media=*, geolocation=*, gyroscope=*, hid=*, interest-cohort=(), keyboard-map=*, magnetometer=*, microphone=*, midi=*, payment=*, publickey-credentials-get=*, screen-wake-lock=*, serial=*, usb=*, web-share=*, xr-spatial-tracking=*"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/only_these/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/only_these/logos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "/only_these/ios/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "/only_these/android/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

# Redirects for PWA assets
[[redirects]]
  from = "/only_these/*"
  to = "/only_these/:splat"
  status = 200

[[redirects]]
  from = "/only_these/logos/*"
  to = "/only_these/logos/:splat"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/firebase-messaging-sw.js"
  to = "/firebase-messaging-sw.js"
  status = 200

# Make sure all static assets are accessible
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# SPA fallback - important for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyB0Nxf3pvW32KBc0D1o2-K6qIeKovhGWfg"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "new1-f04b3.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "new1-f04b3"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "new1-f04b3.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "802463638703"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:802463638703:web:bd0bbdaf3407d784d5205a"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-3RZEW537LN"
  NEXT_PUBLIC_FIREBASE_FCM_VAPID_KEY = "BPAbU0G8rhAKE7ay5RepQ7N3V_CsdCKvmflQm0FncBbx4CHL0IfmGvdbdYUN90Vjn50JB7T9jzj268KhYJ34ikU"
  NEXT_PUBLIC_SUPABASE_URL = "https://yczowovzpltrwhysayzb.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljem93b3Z6cGx0cndoeXNheXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MjE5MjUsImV4cCI6MjA1NzM5NzkyNX0.MdU5GnF8uE6JwItCb2mis-2qUyWUKH7sq2cRzqyncwQ"