[build]
  command = "npm run build"
  # publish = "out" # Removed: Let @netlify/plugin-nextjs handle the publish directory

# Headers to ensure proper content types and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Set proper caching and CORS headers for images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/wolf-icon-white.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "/wolf-icon-black.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

# Asset redirects to ensure images are properly served
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_USE_NETLIFY_EDGE = "true"
  # IMPORTANT: All sensitive environment variables (API keys, secrets, etc.)
  # should be added through the Netlify dashboard UI
  # Client-side vars must use NEXT_PUBLIC_ prefix
  # DO NOT add sensitive values directly in this file

# Explicitly configure service worker files
[[headers]]
  for = "/firebase-messaging-sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/service-worker-fix.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/service-worker-init.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"